name: Spell checking
on: [pull_request_target, push, issue_comment]

jobs:
  build:
    name: Spell checking
    runs-on: ubuntu-latest
    steps:
      - uses: check-spelling/check-spelling@prerelease
        with:
          experimental_apply_changes_via_bot: 1
          checkout: true
