name: Spell checking
on: [pull_request_target, push, issue_comment]

jobs:
  build:
    name: Spell checking
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: check-spelling/check-spelling@prerelease
        with:
          experimental_apply_changes_via_bot: 1
          checkout: true
          extra_dictionaries: 
            cspell:software-terms/dict/softwareTerms.txt
            cspell:typescript/dict/typescript.txt
            cspell:node/dict/node.txt
            cspell:npm/dict/npm.txt
            cspell:css/dict/css.txt
            cspell:html/dict/html.txt
